### ISSUE TITLE
Unclosed Bracket error with Google MDC

### ISSUE THREAD

**Issue by hoomanb** [MadLittleMods/postcss-css-variables#103]
I'm trying to add Google Material design components to a project where `postcss-css-variables` is running. But I'm getting an unclosed bracket error:

https://material.io/develop/web/components/ripples/
```
[15:22:04] Finished 'sass:lint' after 3.71 s
[15:22:04] Starting 'sass:compile'...
[15:22:04] Finished 'sass:block-compile' after 2.6 s
[15:22:06] 'sass:compile' errored after 1.97 s
[15:22:06] CssSyntaxError in plugin "gulp-postcss"
Message:
    /node_modules/@material/ripple/_mixins.scss:182:6: Unclosed bracket

  180 |     @include mdc-feature-targets($feat-structure) {
  181 |       // Retain transform from mdc-ripple-fg-radius-in activation
> 182 |       transform: translate(var(--mdc-ripple-fg-translate-end, 0)) scale(var(--mdc-ripple-fg-scale, 1));
      |      ^
  183 |     }
  184 |   }

```

I think the error above should have enough information, but here's the source code if you need to look further:
https://github.com/material-components/material-components-web/tree/master/packages/mdc-ripple

**Comment by MadLittleMods** [comment]
I am going to close this in favor of https://github.com/MadLittleMods/postcss-css-variables/issues/96
