### ISSUE TITLE
Why i get undefined value

### ISSUE THREAD

**Issue by tigerHeeJS** [MadLittleMods/postcss-css-variables#123]
### version:

`"postcss-css-variables": "^0.17.0"`

### use plugin:
![1](https://user-images.githubusercontent.com/62994244/81272858-a6fc7d00-9080-11ea-8aa6-29905141f9e8.png)

### result:
<img width="436" alt="11" src="https://user-images.githubusercontent.com/62994244/81272882-af54b800-9080-11ea-9281-c76adca0e37f.png">

**Comment by MadLittleMods** [comment]
@tigerHeeJS Please provide your input CSS, the actual result, and your expected result

**Comment by tigerHeeJS** [comment]
Sorry, I saw other issues and learned that the reason is that the `postcss-css-variables` can't automatically recognize DOM structure. I use it like:
```
.a{
  --color1: #ff6100;
}
.b{
color: var(--color1);
}
```
