### ISSUE TITLE
Variable X is undefined and used without a fallback

### ISSUE THREAD

**Issue by J05HI** [MadLittleMods/postcss-css-variables#138]
```
08:53:15 [WARN] [vite] [vite:css] variable --tw-shadow-color is undefined and used without a fallback
1  |  @tailwind base;
2  |  @tailwind components;
3  |  @tailwind utilities;
   |  ^^^^^^^^^^^^^^^^^^^^
4  |  
```

**Comment by MadLittleMods** [comment]
The warning is intended when a variable is used but it isn't defined anywhere.

This report isn't useful on it's own and we need more information (we can re-open the issue):

 - Why isn't `--tw-shadow-color` defined somewhere? Can you share the usage?
 - What is your expectation?
 - What do you see as an ideal way to solve this?
