### ISSUE TITLE
Slow with lots of Rules and Declarations - Performance

### ISSUE THREAD

**Issue by MadLittleMods** [MadLittleMods/postcss-css-variables#15]
@ddprrt wrote this article, [PostCSS misconceptions](https://medium.com/@ddprrt/postcss-misconceptions-faf5dc5038df), which brought to light a huge performance issue. When running just the large Bootstrap codebase with a single variable substitution, it takes 14 seconds to compile(on my system, 5 seconds for @ddprrt). You can find the [test bench that he created, here](https://github.com/ddprrt/postcss-playground/tree/a097faece2b74c0253082eb5faaa3da2f3e80fb0).

I investigated and found that I was foolishly cloning the the whole `root` and then flushing it `node.clone().removeAll()`. I made a `./lib/shallow-clone-node.js` helper to fix this problem.

The testbench now runs at 840ms overall. And when I pre-compile the `postcss-import` step and then run another `process` transform with `postcss-css-variables`, it **now only contributes 230ms**. Still not a stellar performance but a great improvement.

I hope to refactor and rework this whole codebase with [`postcss-selector-parser`](https://github.com/postcss/postcss-selector-parser) which I believe will greatly increase clarity and reduce complexity. The refactor will also give me a fresh start to address performance.

---

*aside:* Thank you Stefan(@ddprrt), for putting some umpf into that performance demo and writing about PostCSS. I really enjoyed your article, [*PostCSS misconceptions*](https://medium.com/@ddprrt/postcss-misconceptions-faf5dc5038df), and I have always viewed PostCSS this way.

**Comment by MadLittleMods** [comment]
Fixed in [v0.4.0](https://github.com/MadLittleMods/postcss-css-variables/releases/tag/v0.4.0) :grinning:

**Comment by ddprrt** [comment]
Wonderful! Great to hear that you could speed that up :+1: 
And yeah, PostCSS (plugin) authors are generally aware of the pros and cons ;-) Which is a good thing, I like that they're open about it
