### ISSUE TITLE
"undefined" cross-file when using postcss-loader

### ISSUE THREAD

**Issue by tj** [MadLittleMods/postcss-css-variables#29]
Specifically I'm using rucksack and postcss-loader in Webpack. `:root` vars in the same file seem to work fine but otherwise the references just output undefined, any suggestions? They work fine if I assign them in JS. thanks!

**Comment by MadLittleMods** [comment]
@tj If the webpack `postcss-loader` is compiling each file separately then we can't see those variables. Can you import the files that contain the variables? https://github.com/postcss/postcss-loader#integration-with-postcss-import

Are other plugins sharing state between subsequent runs?

**Comment by tj** [comment]
hmm I'll check that out, webpack is pretty damn confusing haha, sounds like it's not an issue here though thanks for the pointer!

**Comment by shinzui** [comment]
@tj did you figure out how to make it work?
