### ISSUE TITLE
Update variables without server restart

### ISSUE THREAD

**Issue by admdh** [MadLittleMods/postcss-css-variables#34]
I'm using postcss express middleware and i would like to use variables from external file. Something like this:
```js
var postcss = require('postcss');
var cssvariables = require('postcss-css-variables');
var cssVariables   = require(path.join(__dirname, src, 'cssvariables.js'));
postcss([
    cssvariables({
        variables: cssVariables
        }
    })
])
.process(css, opts);
```
it works just fine but one tiny problem if i modify something in cssvariables.js i will need to restart server to see changes.

There was same issue with postcss-simple-vars and work around was this:
```js
var cssVariables   = path.join(__dirname, src, '_cssVariables.js');

variables: function(){
	delete require.cache[require.resolve(cssVariables)];
	return require(cssVariables);
}
```

So it would be great to see changes without server restart.

**Comment by MadLittleMods** [comment]
You can register a new middleware before your `postcss-middleware` that will run `delete require.cache[require.resolve(cssVariables)];`.

```
app.use(function(req, res, next) {
  delete require.cache[require.resolve(cssVariables)];
  next();
});
```
