### ISSUE TITLE
Node#moveTo was deprecated. Use Container#append

### ISSUE THREAD

**Issue by mikestreety** [MadLittleMods/postcss-css-variables#50]
Hello,

Unfortunately, I don't know enough about node & postCSS to PR, but this notice has started appearing.

```
Node#moveTo was deprecated. Use Container#append
```

They were deprecated in version 6: https://github.com/postcss/postcss/blob/master/CHANGELOG.md#60-marquis-orias

It seems to be used a couple of times in this plugin:

https://github.com/MadLittleMods/postcss-css-variables/search?utf8=%E2%9C%93&q=moveTo&type=

Thanks for a great plugin!

**Comment by KROT47** [comment]
@mikestreety ping
