### ISSUE TITLE
I created an online version for your plugin

### ISSUE THREAD

**Issue by retyui** [MadLittleMods/postcss-css-variables#51]
hi!
I created an online version for your plugin!
What do you think?
https://css-variables.github.io/

**Comment by MadLittleMods** [comment]
This already exists 😕 https://madlittlemods.github.io/postcss-css-variables/playground/

 - Are you aware of the current playground?
 - Anything that should be added to the existing playground?

**Comment by retyui** [comment]
> Are you aware of the current playground? 
> Anything that should be added to the existing playground?

1 no 
2 no

**Comment by MadLittleMods** [comment]
@retyui Is there someway to better expose the existing playground?

It is linked in the repo description at the top and [README](https://github.com/MadLittleMods/postcss-css-variables#code-playground)
