### ISSUE TITLE
Selector which is separated by comma

### ISSUE THREAD

**Issue by bangseongbeom** [MadLittleMods/postcss-css-variables#6]
I expected `.a x, .b x` would be separated into two [ruleset](http://www.w3.org/TR/css-syntax-3/#style-rule) but the output wasn't.

Input:
```
.a {
	--color: red;
}
.b {
	--color: blue;
}

.a x, .b x {
	color: var(--color);
}
```

Real output:
```
.a x, .b x {
	color: blue;
}
```

Expected:
```
.a x {
	color: red;
}

.b x {
	color: blue;
}
```

**Comment by tunnckoCore** [comment]
:+1:

**Comment by MadLittleMods** [comment]
@bangseongbeom Thank you for the bug report and concise input/output expection!

I fixed this issue in the [latest commit](https://github.com/MadLittleMods/postcss-css-variables/commit/b6cd010195f658308621605e9be59f5aefb43316) and added a test so it doesn't regress.
