### ISSUE TITLE
Is this project live?

### ISSUE THREAD

**Issue by equinusocio** [MadLittleMods/postcss-css-variables#68]
Hi, i want to know if this project is still alive. I want to use it and i want to know if it is still supported.

**Comment by MadLittleMods** [comment]
@equinusocio Things mostly work but there are bugs and I am not actively fixing issues that come up (no bandwidth). I can review any PRs submitted though.

**Comment by equinusocio** [comment]
Thank you. #55 and #67 prevent me to use this plugin right now. :(
