### ISSUE TITLE
[Feature] Provide option for non static variables

### ISSUE THREAD

**Issue by QuantumInformation** [MadLittleMods/postcss-css-variables#70]
I have a situation where I just need to support native custom props and want to change them dynamically with js.

**Comment by MadLittleMods** [comment]
> `postcss-css-variables` statically compiles the values. You could use the `preserve` option to also keep the variables in place though, https://github.com/MadLittleMods/postcss-css-variables#preserve-default-false
>
> :point_up: [March 20, 2018 3:36 PM](https://gitter.im/MadLittleMods/postcss-css-variables?at=5ab170da7685a046389cd7ef)
