### ISSUE TITLE
The substituted value 'undefined' when custom property is undefined

### ISSUE THREAD

**Issue by bangseongbeom** [MadLittleMods/postcss-css-variables#8]
When a property is undefined(or can not detect for polyfilling... anyway), substituting to 'undefined' is danger.
The specification says that *[the initial value of a custom property is an empty value](//www.w3.org/TR/css-variables/#syntax)*, but it would be better to leave it just, not to polyfill or substitute.

Input:
```css
.a {
    color: var(--i-am-undefined-property);
}
```

Output:
```css
.a {
    color: undefined;
}
```

Expectation:
```css
.a {
    color: var(--i-am-undefined-property);
}
```

**Comment by MadLittleMods** [comment]
Discussed in #3.

It seems like current behaviour will act the same because `undefined` is an invalid value and will cause the browser to use a inherited version.


Note:

> The initial value of a custom property is an empty value; that is, nothing at all. This initial value has a special interaction with the var() notation, which is explained in the section defining var().
>
>  [*Section 2.1: Custom Property Value Syntax, in CSS Custom Properties for Cascading Variables working draft*](http://www.w3.org/TR/css-variables/#invalid-at-computed-value-time)

> A declaration can be invalid at computed-value time if it contains a var() that references a custom property with its initial value, as explained above, or if it uses a valid custom property, but the property value, after substituting its var() functions, is invalid. When this happens, the computed value of the property is either the property’s inherited value or its initial value depending on whether the property is inherited or not, respectively, as if the property’s value had been specified as the unset keyword.
>
> [*Section 3.1: Invalid Variables, in CSS Custom Properties for Cascading Variables working draft*](http://www.w3.org/TR/css-variables/#invalid-at-computed-value-time)

---

> To substitute a var() in a property’s value:
>
> 1. If the custom property named by the first argument to the var() function is animation-tainted, and the var() function is being used in the animation property or one of its longhands, treat the custom property as having its initial value for the rest of this algorithm.
> 1. If the value of the custom property named by the first argument to the var() function is anything but the initial value, replace the var() function by the value of the corresponding custom property.
> 1. Otherwise, if the var() function has a fallback value as its second argument, replace the var() function by the fallback value. If there are any var() references in the fallback, substitute them as well.
> 1. Otherwise, the property containing the var() function is invalid at computed-value time.
>
> [*Section 3: Using Cascading Variables: the var() notation, in CSS Custom Properties for Cascading Variables working draft*](http://www.w3.org/TR/css-variables/#invalid-at-computed-value-time)

**Comment by bangseongbeom** [comment]
Umm... the 'unset problem' is pretty hard.
If a browser **does not support** css custom property then the browser would **ignore**,
else if the browser **supports** css custom property then the browser would set to **`unset`**.

I was mistaken. Instead of `color: var(--i-am-undefined-property)`, it would be good to be substituted to `unset`.

And additionally, 'undefined' is dangerous if a font named 'undefined' really exists.
```css
.a {
    font-family: undefined;
}
```

**Comment by MadLittleMods** [comment]
I think it is best to leave it to an invalid value so that it falls back properly and I believe will hurt less situations.

Maybe when the major browsers start supporting CSS variables, we can use `unset` to get true functionality.
