### ISSUE TITLE
TypeError in './lib/resolve-value.js' when the value of css-variable is not of string type. 

### ISSUE THREAD

**Issue by shonie** [MadLittleMods/postcss-css-variables#83]
Hello! 

I use your great package with [this postcss.config](https://github.com/shonie/postcss-css-variables-bug-reproduce/blob/master/postcss.config.js). 

I pass plain javascript object with variables to option [**variables**](https://github.com/MadLittleMods/postcss-css-variables#variables-default-). But if any variable is set to not-string value build process crashes with this TypeError.

<img width="1232" alt="screen shot 2018-09-07 at 1 49 37 pm" src="https://user-images.githubusercontent.com/18121238/45215078-f0416b80-b2a4-11e8-87c8-810d940746f0.png">

I've created reproduce repo [here](https://github.com/shonie/postcss-css-variables-bug-reproduce). 

You can do:
```sh
git clone https://github.com/shonie/postcss-css-variables-bug-reproduce.git

npm i

npm start
```

Can i create PR for fixing this?

**Comment by MadLittleMods** [comment]
@shonie PR welcome (add some tests)! 🙂

**Comment by shonie** [comment]
Thank you for your response!

But before rushing into implementation, i want to discuss solution with you. I can propose two methods of fixing this. 

Simplest one is to cast each variable value to string, which is safe, but not transparent.

Other, and, on my opinion better one, is to validate plugin options by some validations tool (something like [schema-utils](https://github.com/webpack-contrib/schema-utils) or [ajv](https://github.com/epoberezkin/ajv).

Me, personally, like schema-utils as it most likely to be already in client's node_modules as webpack uses it under the hood. 

Thank you.

**Comment by shonie** [comment]
I have just now realized that [ajv](https://github.com/epoberezkin/ajv) is strict dependency of [schema-utils](https://github.com/webpack-contrib/schema-utils) 😄

**Comment by MadLittleMods** [comment]
@shonie Casting to string seems reasonable. We already do it for `undefined` -> `'undefined'`, https://github.com/MadLittleMods/postcss-css-variables/pull/44
