### ISSUE TITLE
Is it possible to remove :root in output file while preserve: false? 

### ISSUE THREAD

**Issue by joe223** [MadLittleMods/postcss-css-variables#89]
```diff
  :root {
    --color: red;
  }

  h1 {
    color: var(--color);
  }

  /* becomes */
- :root {
- }
  h1 {
    color: red;
  }
```

**Comment by MadLittleMods** [comment]
@joe223 It seems like it is working for you now so I'll close for now. Feel free to add more details if you can reproduce and we can re-open

**Comment by joe223** [comment]
Thanks！

**Comment by joe223** [comment]
I figure it out！

If we keep CSS comments in `:root` block：
```css
:root {
    /* Something like this*/
}
```
It will preserve in build result. 
Is this a proper feature？ If not，I can make an PR.
